# ================OPENHIM ===============
version: '3.7'
networks:
  openhim:

services:
  #openHIM
  mongo:
    container_name: openhim-mongo
    ports:
      - "27017:27017"
    image: mongo:3.4
    volumes:
      - "mongo-data:/data/db"
    networks:
      - openhim

  core:
    container_name: openhim-core
    image: jembi/openhim-core:v7.1.0
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
    ports:
      - "8088:8080"
      - "5000:5000"
      - "5001:5001"
      - "5050:5050"
      - "5051:5051"
      - "5052:5052"
      - "7788:7788"
    depends_on:
      - mongo
    networks:
      - openhim
  console:
    container_name: openhim-console
    image: jembi/openhim-console:1.14.4
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./config/console-default.json:/usr/share/nginx/html/config/default.json
    networks:
      - openhim

volumes:
  mongo-data:
    name: mongo_data_vol
    driver: local


networks:
  openhim:
    name: openhim.net
    driver: bridge